import "./icons.css";
import iconVisibility from "./svgs/visibility_24px_rounded.svg";
import iconMenu from "./svgs/menu_24px_rounded.svg";
import iconSearch from "./svgs/search_24px_rounded.svg";
import iconArrowBack from "./svgs/arrow_back_24px_rounded.svg";
import iconArrowDownward from "./svgs/arrow_downward_24px_rounded.svg";
import iconArrowUpward from "./svgs/arrow_upward_24px_rounded.svg";
import iconChevronLeft from "./svgs/chevron_left_24px_rounded.svg";
import iconChevronRight from "./svgs/chevron_right_24px_rounded.svg";
import iconChevronDown from "./svgs/chevron_down-24px_rounded.svg";
import iconChevronUp from "./svgs/chevron_up_24px_rounded.svg";
import iconSupervisedUserCircle from "./svgs/supervised_user_circle_24px_rounded.svg";
import iconHome from "./svgs/home_24px_rounded.svg";
import iconClose from "./svgs/close-24px.svg";
import iconImportantNotification from "./svgs/important_notification_24px_rounded.svg";
import { addSvg } from "../svg-utils";

addSvg("omrs-icon-visibility", iconVisibility);
addSvg("omrs-icon-menu", iconMenu);
addSvg("omrs-icon-search", iconSearch);
addSvg("omrs-icon-arrow-back", iconArrowBack);
addSvg("omrs-icon-arrow-downward", iconArrowDownward);
addSvg("omrs-icon-arrow-upward", iconArrowUpward);
addSvg("omrs-icon-chevron-left", iconChevronLeft);
addSvg("omrs-icon-chevron-right", iconChevronRight);
addSvg("omrs-icon-chevron-up", iconChevronUp);
addSvg("omrs-icon-chevron-down", iconChevronDown);
addSvg("omrs-icon-supervised-user-circle", iconSupervisedUserCircle);
addSvg("omrs-icon-home", iconHome);
addSvg("omrs-icon-close", iconClose);
addSvg("omrs-icon-important-notification", iconImportantNotification);
